// Constantes de rotas

export const ROUTE_NAMES = {
  // Auth
  LOGIN: 'Login',
  REGISTER: 'Register',
  PASSWORD_RESET: 'PasswordReset',
  PASSWORD_RESET_CONFIRM: 'PasswordResetConfirm',
  LOGOUT: 'Logout',
  
  // Dashboard
  DASHBOARD: 'Dashboard',
  HOME: 'Home',
  
  // Service Orders
  SERVICE_ORDERS: 'ServiceOrders',
  SERVICE_ORDER_CREATE: 'ServiceOrderCreate',
  SERVICE_ORDER_DETAILS: 'ServiceOrderDetails',
  SERVICE_ORDER_EDIT: 'ServiceOrderEdit',
  SERVICE_ORDERS_KANBAN: 'ServiceOrdersKanban',
  SERVICE_ORDERS_TIMELINE: 'ServiceOrdersTimeline',
  SERVICE_ORDERS_MAP: 'ServiceOrdersMap',
  
  // Organization
  COMPANY_SELECTION: 'CompanySelection',
  COMPANY_SETUP: 'CompanySetup',
  COMPANIES: 'Companies',
  COMPANY_DETAILS: 'CompanyDetails',
  COMPANY_SETTINGS: 'CompanySettings',
  COMPANY_CREATE: 'CompanyCreate',
  COMPANY_EDIT: 'CompanyEdit',
  
  // Financial
  FINANCIAL: 'Financial',
  FINANCIAL_DASHBOARD: 'FinancialDashboard',
  TRANSACTIONS: 'Transactions',
  TRANSACTION_CREATE: 'TransactionCreate',
  TRANSACTION_DETAILS: 'TransactionDetails',
  TRANSACTION_EDIT: 'TransactionEdit',
  RECEIVABLES: 'Receivables',
  RECEIVABLE_DETAILS: 'ReceivableDetails',
  RECEIVABLE_RECEIVE: 'ReceivableReceive',
  PAYABLES: 'Payables',
  PAYABLE_DETAILS: 'PayableDetails',
  PAYABLE_PAY: 'PayablePay',
  INVOICES: 'Invoices',
  INVOICE_DETAILS: 'InvoiceDetails',
  INVOICE_CREATE: 'InvoiceCreate',
  FINANCIAL_CATEGORIES: 'FinancialCategories',
  FINANCIAL_ACCOUNTS: 'FinancialAccounts',
  
  // Clients & Suppliers
  CLIENTS: 'Clients',
  CLIENT_CREATE: 'ClientCreate',
  CLIENT_DETAILS: 'ClientDetails',
  CLIENT_EDIT: 'ClientEdit',
  SUPPLIERS: 'Suppliers',
  SUPPLIER_CREATE: 'SupplierCreate',
  SUPPLIER_DETAILS: 'SupplierDetails',
  SUPPLIER_EDIT: 'SupplierEdit',
  
  // Profile
  PROFILE: 'Profile',
  
  // Users Management
  USERS: 'Users',
  USER_CREATE: 'UserCreate',
  USER_DETAILS: 'UserDetails',
  USER_EDIT: 'UserEdit',
  
  // Roles & Permissions
  ROLES: 'Roles',
  ROLE_DETAILS: 'RoleDetails',
  PERMISSIONS: 'Permissions',
  ROLES_MATRIX: 'RolesMatrix',
  
  // Notifications
  NOTIFICATIONS: 'Notifications',
  NOTIFICATION_SETTINGS: 'NotificationSettings',
  
  // Reports & Analytics
  REPORTS_DASHBOARD: 'ReportsDashboard',
  REPORTS_SERVICE_ORDERS_PERFORMANCE: 'ReportsServiceOrdersPerformance',
  REPORTS_SERVICE_ORDERS_PRODUCTIVITY: 'ReportsServiceOrdersProductivity',
  REPORTS_SERVICE_ORDERS_SATISFACTION: 'ReportsServiceOrdersSatisfaction',
  REPORTS_FINANCIAL_REVENUE: 'ReportsFinancialRevenue',
  REPORTS_FINANCIAL_EXPENSES: 'ReportsFinancialExpenses',
  REPORTS_USERS_ACTIVITIES: 'ReportsUsersActivities',
  REPORTS_CUSTOM: 'ReportsCustom',
  REPORTS_CUSTOM_CREATE: 'ReportsCustomCreate',
  
  // Settings
  SETTINGS_GENERAL: 'SettingsGeneral',
  SETTINGS_SECURITY: 'SettingsSecurity',
  SETTINGS_NOTIFICATIONS: 'SettingsNotifications',
  SETTINGS_INTEGRATIONS: 'SettingsIntegrations',
  SETTINGS_WORKFLOWS_STATES: 'SettingsWorkflowsStates',
  SETTINGS_WORKFLOWS_TEMPLATES: 'SettingsWorkflowsTemplates',
  SETTINGS_PERMISSIONS: 'SettingsPermissions',
  SETTINGS_AUDIT_LOGS: 'SettingsAuditLogs',
  SETTINGS_USER_ACTIVITIES: 'SettingsUserActivities',
  SETTINGS_BACKUP: 'SettingsBackup',
  
  // Transversals
  SEARCH: 'Search',
  FILES: 'Files',
  CALENDAR: 'Calendar',
  ACTIVITY: 'Activity',
  HELP: 'Help',
} as const

export const ROUTE_PATHS = {
  LOGIN: '/login',
  REGISTER: '/register',
  PASSWORD_RESET: '/password-reset',
  PASSWORD_RESET_CONFIRM: '/password-reset/:token',
  DASHBOARD: '/dashboard',
  HOME: '/',
  SERVICE_ORDERS: '/service-orders',
  SERVICE_ORDER_CREATE: '/service-orders/create',
  SERVICE_ORDER_DETAILS: '/service-orders/:id',
  SERVICE_ORDER_EDIT: '/service-orders/:id/edit',
  SERVICE_ORDERS_KANBAN: '/service-orders/kanban',
  SERVICE_ORDERS_TIMELINE: '/service-orders/timeline',
  SERVICE_ORDERS_MAP: '/service-orders/map',
  COMPANY_SELECTION: '/company-selection',
  COMPANY_SETUP: '/company-setup',
  COMPANIES: '/companies',
  COMPANY_CREATE: '/companies/create',
  COMPANY_DETAILS: '/companies/:id',
  COMPANY_EDIT: '/companies/:id/edit',
  COMPANY_SETTINGS: '/companies/:id/settings',
  FINANCIAL: '/financial',
  FINANCIAL_DASHBOARD: '/financial/dashboard',
  TRANSACTIONS: '/transactions',
  TRANSACTION_CREATE: '/transactions/create',
  TRANSACTION_DETAILS: '/transactions/:id',
  TRANSACTION_EDIT: '/transactions/:id/edit',
  RECEIVABLES: '/financial/receivables',
  RECEIVABLE_DETAILS: '/financial/receivables/:id',
  RECEIVABLE_RECEIVE: '/financial/receivables/:id/receive',
  PAYABLES: '/financial/payables',
  PAYABLE_DETAILS: '/financial/payables/:id',
  PAYABLE_PAY: '/financial/payables/:id/pay',
  INVOICES: '/financial/invoices',
  INVOICE_DETAILS: '/financial/invoices/:id',
  INVOICE_CREATE: '/financial/invoices/create',
  FINANCIAL_CATEGORIES: '/financial/categories',
  FINANCIAL_ACCOUNTS: '/financial/accounts',
  CLIENTS: '/clients',
  CLIENT_CREATE: '/clients/create',
  CLIENT_DETAILS: '/clients/:id',
  CLIENT_EDIT: '/clients/:id/edit',
  SUPPLIERS: '/suppliers',
  SUPPLIER_CREATE: '/suppliers/create',
  SUPPLIER_DETAILS: '/suppliers/:id',
  SUPPLIER_EDIT: '/suppliers/:id/edit',
  PROFILE: '/profile',
  USERS: '/users',
  USER_CREATE: '/users/create',
  USER_DETAILS: '/users/:id',
  USER_EDIT: '/users/:id/edit',
  ROLES: '/roles',
  ROLE_DETAILS: '/roles/:role',
  PERMISSIONS: '/permissions',
  ROLES_MATRIX: '/roles/matrix',
  NOTIFICATIONS: '/notifications',
  NOTIFICATION_SETTINGS: '/notifications/settings',
  REPORTS_DASHBOARD: '/reports/dashboard',
  REPORTS_SERVICE_ORDERS_PERFORMANCE: '/reports/service-orders/performance',
  REPORTS_SERVICE_ORDERS_PRODUCTIVITY: '/reports/service-orders/productivity',
  REPORTS_SERVICE_ORDERS_SATISFACTION: '/reports/service-orders/satisfaction',
  REPORTS_FINANCIAL_REVENUE: '/reports/financial/revenue',
  REPORTS_FINANCIAL_EXPENSES: '/reports/financial/expenses',
  REPORTS_USERS_ACTIVITIES: '/reports/users/activities',
  REPORTS_CUSTOM: '/reports/custom',
  REPORTS_CUSTOM_CREATE: '/reports/custom/create',
  SETTINGS_GENERAL: '/settings/general',
  SETTINGS_SECURITY: '/settings/security',
  SETTINGS_NOTIFICATIONS: '/settings/notifications',
  SETTINGS_INTEGRATIONS: '/settings/integrations',
  SETTINGS_WORKFLOWS_STATES: '/settings/workflows/states',
  SETTINGS_WORKFLOWS_TEMPLATES: '/settings/workflows/templates',
  SETTINGS_PERMISSIONS: '/settings/permissions',
  SETTINGS_AUDIT_LOGS: '/settings/audit-logs',
  SETTINGS_USER_ACTIVITIES: '/settings/user-activities',
  SETTINGS_BACKUP: '/settings/backup',
  SEARCH: '/search',
  FILES: '/files',
  CALENDAR: '/calendar',
  ACTIVITY: '/activity',
  HELP: '/help',
} as const

